CREATE TABLE habits (
    id INTEGER NOT NULL UNIQUE,
    habit_name TEXT NOT NULL,
    PRIMARY KEY(id AUTOINCREMENT)
);

CREATE TABLE habit_records (
    id INTEGER NOT NULL UNIQUE,
    habits_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    unit TEXT NOT NULL,
    date TEXT NOT NULL,
    PRIMARY KEY(id AUTOINCREMENT),
    FOREIGN KEY(habits_id) REFERENCES habits(id) ON DELETE CASCADE
);